### PR TITLE
Update to 3.0.7

### PR DESCRIPTION
**Pull request by yohannpoli**
See Change log => http://www.highcharts.com/documentation/changelog

### CODE REVIEW

**Comment by obalais** [comment]
+1

**Comment by yohannpoli** [comment]
Can you please tag this version?

**Comment by ewen** [comment]
Tagged. By the way, I'd recommend migrating to the highcharts.com package as it will be more promptly maintained (by the developers of highcharts).

**Comment by obalais** [comment]
@ewen Yes but we have a problem with hightcharts.com package due to its size while unzipping the tagged version we need.

**Pull request merged**
